### ISSUE TITLE
bug: Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by jcs090218** [ValdezFOmar/tree-sitter-editorconfig#11] opened 2024-10-11 15:10 UTC
### Did you check existing issues?

- [x] I have searched the existing issues of tree-sitter-editorconfig
- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

`0.22.2`

### Describe the bug

```
node:internal/modules/cjs/loader:1544
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\XXX\Documents\_lang\elisp\tree-sitter-langs\repos\editorconfig\grammar.js from C:\Users\JenChieh\Documents\_lang\elisp\tree-sitter-langs\repos\editorconfig\[stdin] not supported.
Instead change the require of grammar.js in C:\Users\XXX\Documents\_lang\elisp\tree-sitter-langs\repos\editorconfig\[stdin] to a dynamic import() which is available in all CommonJS modules.
    at [stdin]:417:16
    at [stdin]-wrapper:6:24 {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.17.0
Node process exited with status 1
```

### Steps To Reproduce/Bad Parse Tree

N/A

### Expected Behavior/Parse Tree

N/A

### Repro

```editorconfig
1. Clone this repo
2. npm install
3. tree-sitter generate
```

**Comment by ValdezFOmar** [comment] 2024-10-12 04:05
> Tree-Sitter CLI Version, if relevant (output of tree-sitter --version)
>
> The latest

Could you please post the actual output of running `tree-sitter --version`?

**Comment by jcs090218** [comment] 2024-10-12 11:21
0.22.2

**Comment by ValdezFOmar** [comment] 2024-10-12 23:44
You are not using the latest version as you claimed, the latest version is [0.24.3](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.24.3). Update your version and try generating the parser again.

**Comment by ValdezFOmar** [comment] 2024-10-13 05:54
@jcs090218 why did you closed it? and why did you mean by "not worth the effort"? if you think that I'm in the wrong here then please explain to me why you think so.

I see that you're trying to use the parser for emacs, but I'm don't know anything about emacs, so I'm probably missing some important info about why you're not able to use the parser. For instance, the parser is use by `nvim-treesitter` and there's no problems reported there about this parser not working.

**Comment by ValdezFOmar** [comment] 2024-11-19 06:01
This issue was most probably caused by using ES modules instead of CommonJS modules. I've reverted that on the latest released.

@jcs090218 if you are still interested, please give it a try again and reopen the issue if any error remains.

**Closed by ValdezFOmar** 2024-11-19 06:01 UTC
Labels: bug

**Comment by jcs090218** [comment] 2024-11-21 07:09
Thanks, I've added this parser to https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/859.
